### ISSUE TITLE
Feature: client mode

### ISSUE THREAD

**Issue by artspb** [duanefields/VirtualKVM#10]
First of all I'd like to thank you for this software. It perfectly solves my problem and I don't have to deal with Synergy or similar stuff. Good job!

So here's the feature request. Each time I disconnect MacBook from iMac, I've to manually disable bluetooth on MacBook, otherwise iMac can't find keyboard and mouse. The idea of the feature is to avoid it. So if the app is installed on MacBook and client mode is enabled, bluetooth will be automatically switched off when Thunderbolt cable became disconnected or Target Display Mode disabled. If it's possible to know current TDM state, it'll probably fix #2.

What do you think?

**Comment by duanefields** [comment]
Yes, this has been suggested before, and I have the same thoughts as you. I've just pushed a branch that has this feature, but I have not had time to test it. If you can test it out and let me know if it works, that'd be great!

**Comment by imyelmo** [comment]
If you could provide an executable or a link to a howto about the compilation process, I could try to test is in a free slot.

**Comment by artspb** [comment]
I've tested it and it works exactly as described. "Auto Toggle Display" option looks quite confusing in the client mode: does it really work? Also I've checked #2 case: client was not able to recognize, that TDM is not available anymore -> bluetooth was still enabled.

**Comment by duanefields** [comment]
It has no effect, I'll hide it

**Comment by duanefields** [comment]
Ok, changes ready for more testing.

**Comment by duanefields** [comment]
Here's a beta....

https://github.com/duanefields/VirtualKVM/releases/tag/v1.1.0

**Comment by artspb** [comment]
Looks good, thank you! #2 is still here, the rest is as usual.

**Comment by duanefields** [comment]
Fixed in 1.1
