### ISSUE TITLE
How to build page

### ISSUE THREAD

**Issue by artspb** [duanefields/VirtualKVM#11]
It's not really difficult to build the project, but it takes some time if you're no a Mac developer. It would be great to describe the process at least shortly. Tricky moments for me were to find, that:

* CocoaPods have to be installed first (`sudo gem install cocoapods`)
* than pod (`pod install`)
* Xcode has to be run from the terminal (`open VirtualKVM.xcworkspace`)

Also I still don't know how to build Release instead of Debug.

**Comment by duanefields** [comment]
You can "Build Archive" to get a release build
