### ISSUE TITLE
Client Mode status not changing

### ISSUE THREAD

**Issue by psu** [duanefields/VirtualKVM#19]
Since my update to El Capitan and VirtualKVM v1.1.2 both MacBook and iMac the Client Mode status is not set correctly both on connecting and disconnecting the iMac.

iMac could be left with Client Mode: Connected even if disconnected and MacBook are left in Client Mode: Not Connected even when connected. 

The Target Display Mode works as usual but I have to change the bluetooth status manually – very annoying since I use a bluetooth keyboard.

**Comment by gschrader** [comment]
You might want to run `/usr/sbin/system_profiler SPThunderboltDataType` and see what is shown. I was trying to figure out why it doesn't work in my setup and have determined that my 2009 iMac doesn't have Thunderbolt and only a mini display port so that's why it doesn't work.

**Comment by psu** [comment]
Thanks for the tip, I will check it out. 
Could this be the case even if it were working with out problems before (other os x version and virtualkvm version)?
Also, as long as the status in virtualkvm is correct it works as expected....
