### ISSUE TITLE
Target display mode not enabled after sleep

### ISSUE THREAD

**Issue by duanefields** [duanefields/VirtualKVM#2]
There's a problem I keep running into where the iMac or the Macbook falls asleep and things can't recover. When I wake them up, Target Display Mode is disabled, and plugging/unplugging the thunderbolt cable doesn't do anything. I've confirmed that the app still recognizes connect/unconnect, but it can't re-enable target display mode.

I'm guessing that because at this point the iMac has no keyboard, the Mac is ignoring the AppleScript key code commands, because the only "fix" is to re-enable bluetooth and connect to the keyboard on the iMac.

**Comment by SoneeJohn** [comment]
@duanefields what you could do is create a power assertion when they are connected.

**Comment by SoneeJohn** [comment]
@duanefields here is quick test implementation:

```objc

#import "ViewController.h"
#import <SJPowerAssertions/SJPowerAssertions.h>
#import "KVMThunderboltObserver.h"

@interface ViewController () <KVMThunderBoltObserverDelegate>

@property (nonatomic, strong) SJPowerAssertions *powerAssetion;

@property (nonatomic, strong) KVMThunderboltObserver *observer;

@end
@implementation ViewController

- (void)viewDidLoad {
    [super viewDidLoad];

    // Do any additional setup after loading the view.
    
    self.powerAssetion = [[SJPowerAssertions alloc]init];
    
    self.observer = [[KVMThunderboltObserver alloc]initWithDelegate:self];
    [self.observer startObserving];
}

#pragma mark - Delegate


- (void)thunderboltObserverDeviceConnected:(KVMThunderboltObserver *)observer{
    
    if (!self.powerAssetion) {
        self.powerAssetion = [[SJPowerAssertions alloc]init];
    }
    [self.powerAssetion createPowerAssertion:@"Connected to Thunderbolt" assertionType:SJPowerAssertionsPreventDisplayIdleSleep];
}
- (void)thunderboltObserverDeviceDisconnected:(KVMThunderboltObserver *)observer{
    
    if (self.powerAssetion) {
        [self.powerAssetion stopHoldingAssertion];
        self.powerAssetion = nil;
    }

}

```

**Comment by SoneeJohn** [comment]
@duanefields I just went and browsed your code and noticed that you're already doing this ;)
