### ISSUE TITLE
Detect Cable On Startup

### ISSUE THREAD

**Issue by cycloon** [duanefields/VirtualKVM#23]
In the current state, then I start the VirtualKVM and the cable is already plugged in, it does not detect it and does not switch to TDM. Would it be possible to change this behavior, so that the application also switches to TDM if the cable is already connected?

Use case is the following: If I boot or reboot the target iMac, it starts without TDM enabled. I would like it to automatically switch to TDM if booted and cable plugged in. (Application is in Login Items and there is a dummy user configured with auto login.)

**Comment by SoneeJohn** [comment]
I believe https://github.com/duanefields/VirtualKVM/pull/27 addresses this. @cycloon can you confirm that the latest build does what you described?

**Comment by SoneeJohn** [comment]
Closed due to no response from OP :-)
