### ISSUE TITLE
Auto Toggle Bluetooth doesn't work in a client mode

### ISSUE THREAD

**Issue by artspb** [duanefields/VirtualKVM#40]
I use macOS 10.12.4 and [VirtualKVM 1.2.2](https://github.com/SoneeJohn/VirtualKVM/releases/download/v1.2.2/VirtualKVM.zip) but the same issue appeared in the previous versions, too.

When I connect a cable iMac is switching to the TDM but Mac Book doesn't enable Bluetooth and I have to enable it manually. When I disconnect a cable Bluetooth is not disabled on Mac Book. At the same time, "Auto Toggle Bluetooth" works fine in a host mode.

**Comment by imyelmo** [comment]
I'm having the same problems as @artspb

**Comment by SoneeJohn** [comment]
I'll look into this sometime this weekend.

**Comment by SoneeJohn** [comment]
@imyelmo @artspb can you test this build: https://github.com/SoneeJohn/VirtualKVM/releases/download/v1.2.2/VirtualKVM.zip ?

**Comment by imyelmo** [comment]
Hi @SoneeJohn , it seems working!!!! Thanks!!! I will report any issue if necessary. Great job!
