### ISSUE TITLE
Thunderbolt 3 and Bluetooth

### ISSUE THREAD

**Issue by dicetomato** [duanefields/VirtualKVM#43]
Are there any known issues with thunderbolt 3 and the bluetooth toggle? I just got a new Macbook Pro and I'm using the thunderbolt 2 to thunderbolt 3 adapter to connect to my iMac. Everything works except bluetooth does not toggle on/off on the Macbook. I'm wondering if it has to do with the thunderbolt converter.

**Comment by SoneeJohn** [comment]
@dicetomato Can you try this version: https://github.com/SoneeJohn/VirtualKVM/releases/download/v1.2.2/VirtualKVM.zip
?

**Comment by dicetomato** [comment]
@SoneeJohn Actually, I ended up getting it working with some troubleshooting. I had to shut off both iMac and MBP a few times. It had been working ever since. I appreciate the reply!

**Comment by SoneeJohn** [comment]
@dicetomato No problem!
