### ISSUE TITLE
Crashes in OSX Sierra 10.12.6

### ISSUE THREAD

**Issue by zandersmith** [duanefields/VirtualKVM#44]
It seems that perhaps the Objective-C API changed in OSX Sierra because the app crashes in KVMThunderboltObserver.m.  In the method isThunderboltEnabled() the call to systemProfilerThunderboltInfo() returns an NSDictionary, not an NSArray.  The following code corrects the problem...

```objc
- (BOOL)isThunderboltEnabled {
    
    NSDictionary *profilerResponse = [self systemProfilerThunderboltInfo];
    
    if (profilerResponse.count >= 1) {
        NSArray *items = profilerResponse[@"_items"];
        
        if (!items || items.count == 0) {
            return NO;
        }
        NSString *busName = items[0][@"_name"];
        
        if ([busName isEqualToString:@"thunderbolt_bus"]) {
            return YES;
        }
        return NO;
    }
    
    return NO;
}
```

After that the app seems to be working well.  I'm having a slight issue with my new wireless keyboard with number pad though.  It seems that two computers can't trade ownership of the keyboard because of a passkey mismatch.  This requires me to turn off and turn on the keyboard again before pairing to the other computer.  Not a showstopper, but let me know if anyone has any ideas.

**Comment by SoneeJohn** [comment]
@zandersmith Do you have the new Apple wireless keyboard? I noticed a this issue on the second generation Apple Magic keyboards.

**Comment by zandersmith** [comment]
@SoneeJohn Yes, just bought the brand new wireless keyboard with number pad.  My older wireless mouse transfers control to the other computer when engaging the target display, but as I mentioned, the keyboard requires a power cycle.
