### ISSUE TITLE
'Host Mode : Ready to Accept Connections' is greyed out

### ISSUE THREAD

**Issue by petertennis** [duanefields/VirtualKVM#53]
I was really hoping this would resolve issue trying to connect my 2016( new gen) MBP to a mid 2011 iMac. Cannot seem to get iMac into Target Display Mode no matter what I try - any suggestions appreciated. 

When I run the tool it seems to be active but plugging in MBP has no effect and I note that in the status bar on the iMac, the 'host mode' status seems to be greyed out as per the subject line above. 

thanks

**Comment by sam1rm** [comment]
Hey @petertennis were you able to figure this out? Struggling on the same thing atm

**Comment by robmcgowan** [comment]
Same issue here. Any ideas?

**Comment by SoneeJohn** [comment]
@petertennis @sam1rm  @robmcgowan  I've been doing some debugging today and it seems to be working better now. You can follow the progress in the [develop branch](https://github.com/duanefields/VirtualKVM/commits/develop). I will push a beta update at the end of the day if you would like to test it out.

**Comment by SoneeJohn** [comment]
@petertennis BTW, the menu is always greyed out because the iMac is passive (when the thunderbolt  port in plugged in then the iMac tries to enable TDM) 

![screen shot 2018-05-10 at 9 01 28 am](https://user-images.githubusercontent.com/4827301/39870853-cf4393fe-5430-11e8-816c-640c5ee62dda.png)

**Comment by SoneeJohn** [comment]
@petertennis  Please see if the latest version fixed you issue [here](https://github.com/duanefields/VirtualKVM/releases/download/v1.2.4/v1_2_4.zip)

**Comment by SoneeJohn** [comment]
@petertennis No problem :-)
