### ISSUE TITLE
mavericks 10.9.4 does not work for me

### ISSUE THREAD

**Issue by Eidan78** [duanefields/VirtualKVM#6]
I've got an iMac 27 late 2009 and a macbook pro 15 late 2013 and this app is not working at all...any help?

thanks! :)

**Comment by aliuk2012** [comment]
Are you able to put your iMac into Target Display Mode?

**Comment by duanefields** [comment]
It works fine for me in Yosemite, 10.10.3, and it worked in Mavericks.

> On Jun 28, 2015, at 3:02 PM, Alistair Laing <notifications@github.com> wrote:
> 
> Are you able to put your iMac into Target Display Mode?
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/duanefields/VirtualKVM/issues/6#issuecomment-116321714>.
> 


—
Duane Fields
duane@duanefields.com

**Comment by duanefields** [comment]
Works in El Cap too
