### ISSUE TITLE
Big Sur

### ISSUE THREAD

**Issue by tuckdesign** [duanefields/VirtualKVM#71]
Did anyone tested this on Big Sur? Need to get cables to connect iMac (late 2014 on Big Sur) with MacBook Pro (Catalina). Will TDM work with Big Sur (11.2.3)?

**Comment by leoneloliveros** [comment]
Same problem

**Comment by yonib05** [comment]
Target display mode is not supported in Late 2014 only until mid 2014 I believe https://support.apple.com/en-us/HT204592
