### ISSUE TITLE
Downloadlink broken

### ISSUE THREAD

**Issue by architector1** [duanefields/VirtualKVM#8]
The link to the release build is broken.

I have downloaded the binary and could run the application from Xcode. The screen will toggle to target display mode. However if I build an application and start it then it doesn't work.

Please provide a ready-to-go release build.

**Comment by duanefields** [comment]
This link doesn't work for you?

https://github.com/duanefields/VirtualKVM/releases/download/v1.0.0/VirtualKVM.zip

**Comment by architector1** [comment]
thanks! this one works. 

but not the one posted at the main page of the project. (https://github.com/duanefields/VirtualKVM/blob/master/releases)

**Comment by duanefields** [comment]
looks like the paths changed… fixed

> On Jul 26, 2015, at 8:38 AM, architector1 <notifications@github.com> wrote:
> 
> thanks! this one works.
> 
> but not the one posted at the main page of the project. (https://github.com/duanefields/VirtualKVM/blob/master/releases <https://github.com/duanefields/VirtualKVM/blob/master/releases>)
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/duanefields/VirtualKVM/issues/8#issuecomment-124988115>.
> 


—
Duane Fields
duane@duanefields.com
